@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternApplyParser" as InternApplyParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "e:EditCommand" as EditCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end  box
box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit 1 d/Line 1 \nLine 2")
activate LogicManager
LogicManager -> InternApplyParser : parseCommand("edit 1 d/Line 1 \nLine 2")
activate InternApplyParser

create EditCommandParser
InternApplyParser -> EditCommandParser
activate EditCommandParser

EditCommandParser -->  InternApplyParser
deactivate EditCommandParser

InternApplyParser -> EditCommandParser : parse("1 d/Line 1 \nLine 2")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand  --> EditCommandParser : e
deactivate EditCommand

EditCommandParser --> InternApplyParser : e
deactivate EditCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> InternApplyParser
destroy EditCommandParser

InternApplyParser --> LogicManager : e
deactivate InternApplyParser

LogicManager -> EditCommand : execute()
activate EditCommand

EditCommand -> Model : setApplication(applicationToEdit, editedApplication)
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : result
deactivate EditCommand

[<--LogicManager
deactivate LogicManager
@enduml
