@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternApplyParser" as InternApplyParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "l:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end  box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list name asc")
activate LogicManager
LogicManager -> InternApplyParser : parseCommand("list name asc")
activate InternApplyParser

create ListCommandParser
InternApplyParser -> ListCommandParser
activate ListCommandParser

ListCommandParser -->  InternApplyParser
deactivate ListCommandParser

InternApplyParser -> ListCommandParser : parse("name asc")
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand
activate ListCommand

ListCommand  --> ListCommandParser : l
deactivate ListCommand

ListCommandParser --> InternApplyParser : l
deactivate ListCommandParser

ListCommandParser -[hidden]-> InternApplyParser
destroy ListCommandParser

InternApplyParser --> LogicManager : l
deactivate InternApplyParser

LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : sortApplications(comparator, sortingOrder);
activate Model

Model --> ListCommand
deactivate Model

ListCommand -> Model : updateFilteredApplicationList(showAllApplications);
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

[<--LogicManager
deactivate LogicManager
@enduml
